<a href="https://colab.research.google.com/github/Amro-source/Deep-Learning/blob/main/RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from __future__ import print_function
import keras
from keras.datasets import cifar10
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
import os

import numpy as np
inputs = np.random.random([32, 10, 8]).astype(np.float32)
simple_rnn = tf.keras.layers.SimpleRNN(4)

output = simple_rnn(inputs)  # The output has shape `[32, 4]`.

simple_rnn = tf.keras.layers.SimpleRNN(
    4, return_sequences=True, return_state=True)

# whole_sequence_output has shape `[32, 10, 4]`.
# final_state has shape `[32, 4]`.
whole_sequence_output, final_state = simple_rnn(inputs)

print(whole_sequence_output)

tf.Tensor(
[[[ 0.6404225   0.66381353 -0.5041805  -0.13479932]
  [ 0.80451894  0.92997944 -0.22366226  0.24602202]
  [ 0.70083916  0.80030423  0.257878    0.4955176 ]
  ...
  [ 0.7989727   0.5873224  -0.1922789   0.868433  ]
  [-0.20773365  0.6686707   0.3122413   0.60449076]
  [ 0.73104525  0.557777   -0.24597466  0.09658748]]

 [[ 0.8088897   0.80314815 -0.77876705 -0.05439016]
  [ 0.8098863   0.92737126 -0.20820981  0.7254595 ]
  [ 0.8581737   0.85250425  0.42953563  0.59679306]
  ...
  [ 0.80008096  0.51718414 -0.11666033  0.75555336]
  [ 0.17621914  0.56956446  0.1906293   0.81155044]
  [ 0.54444474  0.55021274  0.11160046  0.58079684]]

 [[ 0.8802704   0.74046373 -0.74067795  0.3466011 ]
  [ 0.78197575  0.97038764  0.02767166  0.2059795 ]
  [ 0.88000387  0.812048   -0.486695    0.7932504 ]
  ...
  [ 0.70640516  0.74429363  0.24881773  0.4990872 ]
  [ 0.8058702   0.6358522   0.10806591  0.8286148 ]
  [ 0.8456392   0.7882714  -0.5225796   0.9059062 ]]

 ...

 [[ 0.6646085   0.48343